### ISSUE TITLE
TypeError: argument of type 'instance' is not iterable

### ISSUE THREAD

**Issue by unformatt** [jnoortheen/pipm#2]
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin

```
pip install pipm
...
Successfully built pipm
Installing collected packages: pipm
Successfully installed pipm-18.1
```

```
>>> pipm install bunch

Traceback (most recent call last):
  File "/Users/matt/.envs/xxx/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Users/matt/.envs/xxx/lib/python2.7/site-packages/pipm/commands.py", line 145, in run
    file.save(env=options.req_environment, user_reqs=result)
  File "/Users/matt/.envs/xxx/lib/python2.7/site-packages/pipm/file.py", line 253, in save
    setup_cfg.add_requirements(user_reqs, env)
  File "/Users/matt/.envs/xxx/lib/python2.7/site-packages/pipm/setup_cfg.py", line 96, in add_requirements
    update_config(config, base_key, key, reqs)
  File "/Users/matt/.envs/xxx/lib/python2.7/site-packages/pipm/setup_cfg.py", line 46, in update_config
    if base_key not in config:
TypeError: argument of type 'instance' is not iterable
```

**Comment by jnoortheen** [comment]
Check with the new version `18.3`. It fixes all failing Py2 test cases including yours.
