### ISSUE TITLE
Doesn't work inside pyenv virtualenv

### ISSUE THREAD

**Issue by Panamus** [jnoortheen/pipm#5]
Installed this with the hope of moving away from pipenv 

Running within pyenv virtualenv for python 3.7 throws a ModuleNotFound error.

```
Traceback (most recent call last):
  File "/Users/developer-3/.pyenv/versions/leadflo/bin/pipm", line 5, in <module>
    from pipm.__main__ import main
  File "/Users/developer-3/.pyenv/versions/leadflo/lib/python3.7/site-packages/pipm/__main__.py", line 20, in <module>
    from pipm.commands import (
  File "/Users/developer-3/.pyenv/versions/leadflo/lib/python3.7/site-packages/pipm/commands.py", line 8, in <module>
    from . import file
  File "/Users/developer-3/.pyenv/versions/leadflo/lib/python3.7/site-packages/pipm/file.py", line 8, in <module>
    from pip._internal.download import PipSession, get_file_content
ModuleNotFoundError: No module named 'pip._internal.download'
```

```
$ pip --version     
pip 20.1 from /Users/developer-3/.pyenv/versions/leadflo/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by jnoortheen** [comment]
what is the version of `pipm`? you could view by `pip show pipm`

**Comment by Panamus** [comment]
`pipm-19.3.5`

seems that's what's on pypi

**Comment by jnoortheen** [comment]
seems like the latest release failed. I will run it again.

**Comment by jnoortheen** [comment]
I have pushed a new [version](https://pypi.org/project/pipm/) that support `pip>=20.1`
